# Site settings
title: Vinicius Senna
baseurl: "/slim"
url: "http://vsenna.github.com"

# Build settings
#markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 
